-- DEMO DATA. Every row is prefixed DEMO and slugged demo-*.
-- Remove with:  delete from public.strains where slug like 'demo-%';

insert into public.strains (slug,name,parent_a,parent_b,flavor,status,qty,visible,featured,sort,batch_name,batch_no,harvest,release_label,teaser,aroma,appearance,cultivation,description,pricing) values ('demo-gelato-41','DEMO Gelato 41','Sunset Sherbet','Thin Mint GSC',array['Sweet','Creamy','Gas']::text[],'AVAILABLE',42,true,true,0,'Candy Room 04','DEMO-G41-0426','Apr 2026','','','Sherbet, cold cream, faint diesel','Dense, purple-shot, heavy frost','Indoor, 9-week flower, hand-trimmed, 14-day slow cure','DEMO DATA — sample listing to confirm the database is connected. Not real inventory.','[{"label":"Eighth","price":"$45"},{"label":"Quarter","price":"$85"},{"label":"Ounce","price":"$280"},{"label":"Pound","price":"Contact for wholesale"}]'::jsonb) on conflict (slug) do nothing;
insert into public.strains (slug,name,parent_a,parent_b,flavor,status,qty,visible,featured,sort,batch_name,batch_no,harvest,release_label,teaser,aroma,appearance,cultivation,description,pricing) values ('demo-candy-paint','DEMO Candy Paint','Zkittlez','Grape Gas',array['Berry','Sugar','Fuel']::text[],'AVAILABLE',28,true,false,1,'Candy Room 05','DEMO-CDP-0426','Apr 2026','','','Crushed berry, solvent, violet','Glossy, deep violet bracts','Indoor, 10-week flower, single-plant selection','DEMO DATA — sample listing to confirm the database is connected. Not real inventory.','[{"label":"Eighth","price":"$50"},{"label":"Ounce","price":"$320"}]'::jsonb) on conflict (slug) do nothing;
insert into public.strains (slug,name,parent_a,parent_b,flavor,status,qty,visible,featured,sort,batch_name,batch_no,harvest,release_label,teaser,aroma,appearance,cultivation,description,pricing) values ('demo-sherbhead','DEMO Sherbhead','Sherbinski''s Mint','Headband',array['Citrus','Mint','Pine']::text[],'LOW STOCK',6,true,false,2,'Candy Room 03','DEMO-SHB-0326','Mar 2026','','','Lime peel, mint, resin','Spear-shaped, pale green, long pistils','Indoor, 9-week flower, low-stress trained','DEMO DATA — tests the LOW STOCK badge. Not real inventory.','[{"label":"Eighth","price":"$40"},{"label":"Ounce","price":"$250"}]'::jsonb) on conflict (slug) do nothing;
insert into public.strains (slug,name,parent_a,parent_b,flavor,status,qty,visible,featured,sort,batch_name,batch_no,harvest,release_label,teaser,aroma,appearance,cultivation,description,pricing) values ('demo-peach-ringz','DEMO Peach Ringz','Peach Ozz','Runtz',array['Stonefruit','Sugar','Cream']::text[],'SOLD OUT',0,true,false,3,'Candy Room 02','DEMO-PRZ-0226','Feb 2026','','','Peach skin, sugar, whipped cream','Round, orange-haired, sticky','Indoor, 9-week flower, small 12-plant run','DEMO DATA — tests the SOLD OUT state. Not real inventory.','[]'::jsonb) on conflict (slug) do nothing;
insert into public.strains (slug,name,parent_a,parent_b,flavor,status,qty,visible,featured,sort,batch_name,batch_no,harvest,release_label,teaser,aroma,appearance,cultivation,description,pricing) values ('demo-sunset-rntz','DEMO Sunset Rntz','Runtz','Sunset Sherbet',array['Tropical','Gas','Vanilla']::text[],'COMING SOON',0,true,false,4,'Candy Room 06','DEMO-SRZ-0526','May 2026','May 2026','DEMO DATA — tests the upcoming drops section.','Mango, vanilla bean, faint gas','Chunky, cream-coloured trichome cover','Indoor, 10-week flower, currently in cure','DEMO DATA — tests the COMING SOON state. Not real inventory.','[]'::jsonb) on conflict (slug) do nothing;

insert into public.inquiries (name,phone,email,strain,message,status,source_page) values ('DEMO — R. Alvarez','+1 (415) 555-0114','demo@example.com','DEMO Gelato 41','DEMO DATA — sample inquiry to confirm the inquiries table works.','NEW','/strains/demo-gelato-41');
insert into public.inquiries (name,phone,email,strain,message,status,source_page) values ('DEMO — Sunset Collective','+1 (707) 555-0188','demo2@example.com','DEMO Candy Paint','DEMO DATA — second sample inquiry, marked replied.','REPLIED','/strains/demo-candy-paint');
